"""empty message

Revision ID: 6bced34304d8
Revises: f3269d46fe10
Create Date: 2019-03-09 21:04:42.433708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bced34304d8'
down_revision = 'f3269d46fe10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile')
    # ### end Alembic commands ###
