"""empty message

Revision ID: 892e4e1d3660
Revises: 3345d324592d
Create Date: 2019-06-04 22:22:21.269150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892e4e1d3660'
down_revision = '3345d324592d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('flight_type', sa.Enum('one_way', 'round_trip', name='TypeEnum'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('flight_seat_id', sa.Integer(), nullable=False),
    sa.Column('return_flight_id', sa.Integer(), nullable=True),
    sa.Column('return_flight_seat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flight.id'], ),
    sa.ForeignKeyConstraint(['flight_seat_id'], ['flight_seats.id'], ),
    sa.ForeignKeyConstraint(['return_flight_id'], ['flight.id'], ),
    sa.ForeignKeyConstraint(['return_flight_seat_id'], ['flight_seats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    # ### end Alembic commands ###
