"""empty message

Revision ID: 92934fa377d3
Revises: e2ea6c53837b
Create Date: 2019-05-09 01:31:45.054745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92934fa377d3'
down_revision = 'e2ea6c53837b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('airline', sa.Integer(), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=False),
    sa.Column('departure_location', sa.String(length=50), nullable=False),
    sa.Column('arrival_location', sa.String(length=50), nullable=False),
    sa.Column('flight_code', sa.String(length=10), nullable=False),
    sa.Column('no_of_seats', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('cancelled', 'active', 'unknown', name='myenum'), nullable=False),
    sa.ForeignKeyConstraint(['airline'], ['airline.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight_seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('seat', sa.String(length=3), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flight.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight_seats')
    op.drop_table('flight')
    # ### end Alembic commands ###
