"""empty message

Revision ID: 9832fc315d87
Revises: 892e4e1d3660
Create Date: 2019-06-10 00:14:25.949995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9832fc315d87'
down_revision = '892e4e1d3660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('ticket_code', sa.String(length=7), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'ticket_code')
    # ### end Alembic commands ###
